# Use the latest 2.1 version of CircleCI pipeline process engine. 
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:

  node: circleci/node@4.1


jobs:

  build-and-test:  

    docker:
      - image: circleci/php:7.1-apache-node-browsers
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD
      - image: cimg/node:15.1
      - image: circleci/mysql:5.7
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD
        environment:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: food_test
          MYSQL_USER: admin
          MYSQL_PASSWORD: root


    steps:

      - checkout

      - node/install-packages

      - run:
          name: Waiting for MySQL to be ready
          command: |
            for i in `seq 1 10`;
            do
              nc -z 127.0.0.1 3306 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for MySQL && exit 1
      - run:
          name: Install MySQL CLI; Import dummy data; run an example query
          command: |
            sudo apt-get update
            sudo apt-get install default-mysql-client
            mysql -h 127.0.0.1 -u admin -proot food_test < sql_data/dummy.sql
            mysql -h 127.0.0.1 -u admin -proot --execute="SELECT * FROM food_test.users"
            mysql -h 127.0.0.1 -u admin -proot --execute="SELECT * FROM food_test.food_option"
      - run:
          name: Run tests
          command: npm test

workflows:
  sample: 
    jobs:
      - build-and-test